/**
 * This file defines the color palette for the app, with separate values for light and dark themes.
 */

export const Colors = {
  light: {
    text: '#111c11ff',
    textSecondary: '#666',
    textMuted: '#888',
    textInverse: '#fff',
    background: '#fff',
    card: '#fff',
    cardBorder: '#e0e0e0',
    cardHighlight: '#f0f9ff',
    inputBackground: '#fff',
    inputBorder: '#ddd',
    placeholder: '#888',
    separator: '#eee',
    reply: '#f9f9f9',
    deleteBackground: '#ffebee',
    tint: '#0aa436ff',
    icon: '#68766aff',
    tabIconDefault: '#68766cff',
    tabIconSelected: '#0aa436ff',
    primary: '#4CAF50',
    primaryText: '#fff',
    danger: '#bd0000',
    dangerText: '#fff',
    error: '#d32f2f',
    link: '#007AFF',
    headerBackground: '#A1CEDC',
    overlay: 'rgba(0,0,0,0.4)',
    retake: '#888',
  },
  dark: {
    text: '#eceeecff',
    textSecondary: '#aaa',
    textMuted: '#777',
    textInverse: '#fff',
    background: '#151815ff',
    card: '#1e1e1e',
    cardBorder: '#333',
    cardHighlight: '#1a2e1a',
    inputBackground: '#2a2a2a',
    inputBorder: '#555',
    placeholder: '#888',
    separator: '#333',
    reply: '#1a1a1a',
    deleteBackground: '#3d1111',
    tint: '#fff',
    icon: '#9ba69eff',
    tabIconDefault: '#9ba69eff',
    tabIconSelected: '#fff',
    primary: '#4CAF50',
    primaryText: '#fff',
    danger: '#bd0000',
    dangerText: '#fff',
    error: '#ff6b6b',
    link: '#4CAF50',
    headerBackground: '#1D3D47',
    overlay: 'rgba(0,0,0,0.6)',
    retake: '#666',
  },
};